### ISSUE TITLE
AttributeError: 'EntropyBottleneck'

### ISSUE THREAD

**Issue by pavan-dharimireddy** [RenYang-home/OpenDVC#22]
getting this error whenever i  tried to run the psnr.py and other files

***AttributeError: 'EntropyBottleneck' object has no attribute '_assert_input_compatibility'***
included the tensorflow_compression library ,  i am using python==3.7 and tensorflow==1.13.0 because tensorflow==1.12.0 is not downloading for me,
except tensorflow libraries i installed all other libraries which are there in requirements.txt with exact versions

**Comment by RenYang-home** [comment]
Our pre-trained models are only compatible with tf 1.12, and cannot be used for tf 1.13, since we train with tensorflow-compression 1.0, which is only compatible with tf 1.12. However, you could use our training codes to train your own model with TensorFlow 1.13 and the corresponding version of tensorflow-compression.

**Comment by pavan-dharimireddy** [comment]
Thank you for your response
