### ISSUE TITLE
Unable to reproduce the reported bit rate results comparing to H. 265

### ISSUE THREAD

**Issue by ghazalsahebzamani** [RenYang-home/OpenDVC#4]
Hi,

First of all, thank you very much for taking the time to provide an open-source implementation for this paper. I had a question regarding deploying this method. I'm using PSNR 1024 model to compress random videos (I had tried samples of different resolution or fps). Then I compress the same video using H. 265 with CRF=28. However, for all of them, the compressed results of the OpenDVC method give me a size of about two times that of achieved with H. 265 ( Although it works for the sample basketball pass video provided). Is there anything I'm missing?

**Comment by RenYang-home** [comment]
Hi,

Thanks for trying out our codes. 

1. How about the PSNR of the H.265 compressed and the OpenDVC compressed videos? Because it is meaningful to compare size (bit-rates) only if when having the same compression quality. Therefore, we usually compare the rate-distortion curves, as shown at the end of this Github readme.

2. What H.265 configuration did you use? As claimed in the original DVC paper (see Appendix B in https://arxiv.org/pdf/1812.00101.pd), the x265 zero latency veryfast mode is used. If you are using the default x265, or even higher configurations, it will obviously outperform DVC in terms of PSNR. The learned compression is still in an initial stage, we are working on improving the performance until it outperforms the handcrafted standards, such as H.265 and VVC, in the future.

3. What kind of video did you use? Different from the handcrafted standard, every learned method suffers from the generalization problem. If the distribution of test video is hugely different from the training samples, the performance will drop, e.g., we do not have cartoon videos in training set. But the test videos we used are very typical, which are used to evaluate the video coding standards, so I think our trained model is able to generalize to most common videos.
