### ISSUE TITLE
I frame coding

### ISSUE THREAD

**Issue by Lithium07** [RenYang-home/OpenDVC#8]
Hi Yang, Thanks for sharing your source code. I have a question about the I frame coding. From your code, I see that you use BPG as the I-frame coding. Actually, the coding performance of BPG is much higher than that of I frame coding in x265 (very fast). The quality of I frame also has a large influence on the following P frame coding.  So I think that the comparison between OpenDVC and x265 (shown in Fig. 3 in your technical report) may not be fair. If I have a wrong understanding, please tell me.

**Comment by RenYang-home** [comment]
Yes, you are right. The target of learned video compression is to utilize an end-to-end framework to compress video and compare with traditional standards, e.g., x265. Here we just use a simple way to compress I frames, since the compression of the I frame is out of the scope of this code. However, please note that the state-of-the-art learned image compression methods:

Minnen et al., Joint Autoregressive and Hierarchical Priors for Learned Image Compression. NeurIPS 2018
Lee et al., Context-adaptive Entropy Model for End-to-end Optimized Image Compression, ICLR 2019
Hu et al., Coarse-to-Fine Hyper-Prior Modeling for Learned Image Compression, AAAI 2020

have already beaten BPG. Therefore, in theory, the I frames can be compressed with these learned methods to achieve equivalent or even better performance than this code, and in this way, all frames are compressed via end-to-end deep networks.

**Comment by Lithium07** [comment]
Thanks for clarifying it.
